mode = "release"

[server]
port = 8000
secret = "ssss"

[database]
type = "postgres"
host = "localhost"
user = "postgres"
password = "admin"
dbname = "postgres"
port = 5432

[redis]
host = "localhost"
port = 6379
password = ""
db = 0