basePath: /api
definitions:
  request_model.AdminUserLoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: hukai2943@aliyun.com
    name: noobHuKai
    url: https://github.com/noobHuKai
  description: This is a go template server.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Golang Template API
  version: "1.0"
paths:
  /api/admin/login:
    post:
      consumes:
      - application/json
      description: Administrator Login
      parameters:
      - description: login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request_model.AdminUserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Login
      tags:
      - admin
swagger: "2.0"
