basePath: /api
host: localhost:8000
info:
  contact:
    email: hukai2943@aliyun.com
    name: noobHuKai
    url: https://github.com/noobHuKai
  description: This is a go template server.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Golang Template API
  version: "1.0"
paths:
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
